language: node_js
node_js:
  - '8'

before_install: cd react-frontend

jobs:
  include:
    - stage: "Tests"
      name: "Quality Test"
      script: 
        npm run lint
    - stage: deploy
      name: "deploy to firebase"
      before_script: npm install firebase-tools -g
      script: 
        CI=false npm run build && firebase deploy --only hosting --token "1//01QaCswrK88a-CgYIARAAGAESNwF-L9IrOfFHMiOcns2j-KAyQAF2C7cN9CdI_8iPz3gLJ1gy1Lp1ENZY_hoUnA5Psl3-BaCJPCE"